# Generated by Django 2.2.5 on 2019-11-06 06:38

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='annapurna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.BigIntegerField()),
                ('district', models.CharField(max_length=50)),
                ('dan', models.CharField(max_length=50)),
                ('das', models.IntegerField()),
                ('gapa_napa', models.CharField(max_length=50)),
                ('type_gn', models.CharField(max_length=50)),
                ('gn_code', models.FloatField()),
                ('new_ward_n', models.BigIntegerField()),
                ('ddgnww', models.FloatField()),
                ('center', models.CharField(max_length=50)),
                ('state_code', models.IntegerField()),
                ('ddgn', models.BigIntegerField()),
                ('area_sqkm', models.FloatField()),
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='school',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('Type', models.CharField(blank=True, max_length=40)),
            ],
        ),
    ]
