# Generated by Django 2.2.5 on 2019-11-15 16:46

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='annapurna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.BigIntegerField()),
                ('dcode', models.IntegerField()),
                ('district', models.CharField(max_length=50)),
                ('dan', models.CharField(max_length=50)),
                ('das', models.IntegerField()),
                ('gapa_napa', models.CharField(max_length=50)),
                ('type_gn', models.CharField(max_length=50)),
                ('gn_code', models.FloatField()),
                ('new_ward_n', models.BigIntegerField()),
                ('ddgnww', models.FloatField()),
                ('center', models.CharField(max_length=50)),
                ('state_code', models.IntegerField()),
                ('ddgn', models.BigIntegerField()),
                ('area_sqkm', models.FloatField()),
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Annapurna',
            },
        ),
        migrations.CreateModel(
            name='gpx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('elevation', models.FloatField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name=(models.FloatField(), models.FloatField()))),
            ],
        ),
        migrations.CreateModel(
            name='school',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('principal_name', models.CharField(blank=True, max_length=40)),
                ('no_of_buildings', models.FloatField(blank=True, null=True)),
                ('no_of_staffs', models.FloatField(blank=True, null=True)),
                ('no_of_students', models.FloatField(blank=True, null=True)),
                ('school_location', models.CharField(choices=[('wardno1', 'Ward No 1'), ('wardno2', 'Ward No 2'), ('wardno3', 'Ward No 3'), ('wardno4', 'Ward No 4'), ('wardno5', 'Ward No 5'), ('wardno6', 'Ward No 6'), ('wardno7', 'Ward No 7'), ('wardno8', 'Ward No 8'), ('wardno9', 'Ward No 9'), ('wardno10', 'Ward No 10'), ('wardno11', 'Ward No 11')], max_length=40, null=True)),
                ('status', models.CharField(choices=[('updated', 'Updated'), ('notupdated', 'Not Updated')], default='updated', max_length=20, null=True)),
                ('contact', models.CharField(blank=True, max_length=10, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('Type', models.CharField(blank=True, choices=[('Government', 'Government'), ('Private', 'Private')], max_length=40)),
            ],
        ),
    ]
