# Generated by Django 2.2.5 on 2019-11-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpx',
            name='location',
        ),
        migrations.AddField(
            model_name='gpx',
            name='field',
            field=models.CharField(choices=[('School', 'School'), ('Annapurna', 'Annapurna')], max_length=40, null=True),
        ),
    ]
