# Generated by Django 2.2.5 on 2019-11-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annapurna',
            name='dcode',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
