# Generated by Django 2.2.5 on 2019-12-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20191116_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(default='Null', max_length=100),
        ),
        migrations.AlterField(
            model_name='school',
            name='principal_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_location',
            field=models.CharField(choices=[('1', 'Ward No 1'), ('2', 'Ward No 2'), ('3', 'Ward No 3'), ('4', 'Ward No 4'), ('5', 'Ward No 5'), ('6', 'Ward No 6'), ('7', 'Ward No 7'), ('8', 'Ward No 8'), ('9', 'Ward No 9'), ('10', 'Ward No 10'), ('11', 'Ward No 11')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='status',
            field=models.CharField(choices=[('updated', 'Updated'), ('notupdated', 'Not Updated')], default='Not Updated', max_length=20, null=True),
        ),
    ]
