# Generated by Django 2.2.5 on 2019-11-13 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_annapurna_dcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annapurna',
            options={'verbose_name_plural': 'Annapurna'},
        ),
    ]
