# Generated by Django 2.2.5 on 2019-10-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='Type',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
