# Generated by Django 2.2.5 on 2019-10-03 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_school_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pointofinterests',
        ),
    ]
