# Generated by Django 2.2.5 on 2019-11-05 04:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_delete_pointofinterests'),
    ]

    operations = [
        migrations.CreateModel(
            name='annapurna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid_1', models.BigIntegerField()),
                ('objectid', models.BigIntegerField()),
                ('palika', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('gapa_napa', models.CharField(max_length=50)),
                ('gn_type', models.CharField(max_length=50)),
                ('province', models.BigIntegerField()),
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
